import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'FaxChat App',
  description: 'Generated by create next app',
    icons: {
      icon: {
        url: "/logo.png",
        type: "image/png",
      },
      shortcut: { url: "/logo.png", type: "image/png" },
    },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link rel="icon" href="\logo.png" type="image/png" sizes="any"></link>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
